# Site settings
title: Luca Ananias
description: Luca Ananias' Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Luca Ananias
user_description: > 
  I'm currently a Computer Science undergraduate at Federal University of Pernambuco's Informatics Center, Recife, Brazil.
  I also work at Voxar Labs, as a member of their rendering team. My main interests are Realtime and Offline Rendering and 
  Virtual and Augmented Reality.
user_title: CS Undergraduate and CG Researcher
email: lams3@cin.ufpe.br
github_username:  lams3
#TODO linkedin_username: lams3
#TODO facebook_username: lams3
#twitter_username: lorem_ipsum
#gplus_username:  lams3

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
